- name: Playbook to get getting the top 10 CPU consuming process
  hosts: localhost
  tasks:
    - name: Top 10 CPU consuming processes
      shell: ps -eo pid,user,ppid,%cpu --sort=-%cpu | head -10
      register: top_cpu

    - debug:
        msg: "{{ top_cpu.stdout_lines }}"


    - name: Top 10 Memory consuming processes
      shell: ps -eo pid,user,ppid,%mem --sort=-%mem | head -10
      register: top_memory

    - debug:
        msg: "{{ top_memory.stdout_lines }}"

